-- Add AI recap columns to events table.
-- ai_event_summary: 2-3 sentence post-event recap generated by Gemini via Edge Function.
-- ai_golfer_insights: JSONB object keyed by golfer_id, one sentence per non-guest golfer.
-- Both are nullable; null means not yet generated or generation failed.
-- Written only by the generate-event-recap Edge Function (service role).
-- Anon role gets read access via the existing table-level SELECT policy.

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS ai_event_summary text,
  ADD COLUMN IF NOT EXISTS ai_golfer_insights jsonb;

-- Explicit anon read grant in case column-level security is in use.
-- If your policy is table-level SELECT for anon this is a no-op (safe to run).
GRANT SELECT (ai_event_summary, ai_golfer_insights) ON events TO anon;
